{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chatgpt-telegram-bot.fullname" . }}
  labels:
    {{- include "chatgpt-telegram-bot.labels" . | nindent 4 }}
stringData:
  openaiToken: {{ .Values.configuration.openaiToken }}
  telegramToken: {{ .Values.configuration.telegramToken }}
data:
  {{- toYaml .Values.secret.values | nindent 2 }}
{{- end }}